### ISSUE TITLE
Breakfast Discussion

### ISSUE THREAD

**Issue by amypaddle1** [IntroToCode/CodeMates7_Fall22#1]
## 💬 Discussion topic

Breakfast ideas?!

## ❗ Potential issues

What's your favorite breakfast?
Any allergies or dietary restrictions?
How many people are eating this breakfast? 

## 👥 People to consult

@p-mullangi 
@carolinadarraidou
@gurbuxlohana
@rnagpal991

## 📃 Details

I love breakfast cookies--esp browned butter chocolate chip cookies from The Good Life Grocery in Bernal Heights
Am mostly vegetarian

**Comment by carolinadarraidou** [comment]
I love pancakes in the morning with syrup, and I don't have any allergies.

**Comment by rnagpal991** [comment]
I love a simple english breakfast complete with fried eggs, bacon, and mashed potatoes - I don't have any allergies

**Comment by rnagpal991** [comment]
Let's finalize a recipe and assign each section to a team member - that way all of us will have contributed and we can review each other's sections

**Comment by amypaddle1** [comment]
Sounds good to me @rnagpal991, should we go forward with a recipe for 5 people?

Unfortunately I'm allergic to egg whites and don't get a lot of joy from fried eggs anymore... 

How would you feel about a breakfast smoothie or oatmeal with fruit?! Trying to think of something easy (and maybe a little heart healthier than my initial post lol) 🙈

**Comment by carolinadarraidou** [comment]
I agree with oatmeal with fruit. Sounds simple and delicious!

**Comment by p-mullangi** [comment]
Merged pull request to address this issue

**Comment by p-mullangi** [comment]
Merged pull request to address this issue
