### ISSUE TITLE
Dinner discussion

### ISSUE THREAD

**Issue by rnagpal991** [IntroToCode/CodeMates7_Fall22#2]
## 💬 Discussion topic

Dinner discussion

## ❗ Potential issues

Dish to prepare
Allergies, if any
Number of people to be served

## 👥 People to consult

@p-mullangi
@carolinadarraidou
@gurbuxlohana
@amypaddle1

## 📃 Details

I love nicely seasoned Italian white sauce pasta - chicken alfredo recipes are my go-to!

**Comment by amypaddle1** [comment]
I'm ok with chicken Alfredo! 

No allergies here.

Shall we cook for 6 so that we have some leftovers? 😋

**Comment by carolinadarraidou** [comment]
I agree, I love chicken alfredo as well and have no allergies!

**Comment by p-mullangi** [comment]
Merged pull request to address this issue
